from ubi/ubi9

ARG SLURM_VERSION=

# git for downloading repo.
# libjwt for jwt authentication

RUN dnf install git bz2

ARG MUNGE_UID=1100
ARG MUNGE_GID=1100
RUN groupadd -g $MUNGE_GID munge
RUN useradd -m -u $MUNGE_UID -g $MUNGE_GID -s /bin/bash munge

RUN dnf install munge munge-devel

ARG SLURM_UID=1101
ARG SLURM_GID=1101
RUN groupadd -g $SLURM_GID slurm
RUN useradd -m -u $SLURM_UID -g $SLURM_GID -s /bin/bash slurm

RUN dnf install make


COPY slurm-23.11.5 /opt

WORKDIR /opt/slurm-23.11.5

RUN ./configure --with-jwt

RUN make

