services:

  slurmctld:
    image: localhost/sssd-slurm
    container_name: slurmctld
    hostname: slurmctld
    volumes:
      - ${PWD}/configs/slurm.conf:/opt/slurm/etc/slurm.conf:z
      #- ${PWD}/statedir:/var/spool/slurmctld:z
      - type: tmpfs 
        target: /run/munge
        tmpfs:
          size: 1048576
          mode: 1755
      - type: tmpfs 
        target: /var/spool/slurmctld
        tmpfs:
          size: 524288000
          mode: 1600
    ports:
      - "6817:6817"
    depends_on:
      - slurmdbd
      - mariadb
    command: ./entrypoint.sh slurmctld

  slurmdbd:
    image: localhost/sssd-slurm
    container_name: slurmdbd
    hostname: slurmdbd
    volumes:
      - ${PWD}/configs/slurmdbd.conf:/opt/slurm/etc/slurmdbd.conf:z
      - ${PWD}/configs/slurm.conf:/opt/slurm/etc/slurm.conf:z
      - type: tmpfs 
        target: /run/munge
        tmpfs:
          size: 1048576
          mode: 1755
      - type: tmpfs 
        target: /var/spool/slurmdbd
        tmpfs:
          size: 104857600
          mode: 1600
    ports:
      - "6819:6819"
    depends_on:
      - mariadb
    command: ./entrypoint.sh slurmdbd

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    hostname: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: secretpassword
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: database_mgr
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
     - type: tmpfs 
       target: /var/lib/mysql
       tmpfs:
         size: 524288000
         mode: 1660
     #- ${PWD}/mariadb:/var/lib/mysql:z
     
    

